# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty

# Server
auto:         true
source:       ./docs
destination:  ./_gh_pages
url:          http://todc-bootstrap.dev:9002
server_port:  9002
baseurl:      ""
# baseurl:      /todc-bootstrap-3
